export const USER_MENTOR_REGISTER_REQUEST = "USER_MENTOR_REGISTER_REQUEST";
export const USER_MENTOR_REGISTER_SUCCESS = "USER_MENTOR_REGISTER_SUCCESS";
export const USER_MENTOR_REGISTER_FAIL = "USER_MENTOR_REGISTER_FAIL";

export const USER_MENTEE_REGISTER_REQUEST = "USER_RMENTEE_EGISTER_REQUEST";
export const USER_MENTEE_REGISTER_SUCCESS = "USER_MENTEE_REGISTER_SUCCESS";
export const USER_MENTEE_REGISTER_FAIL = "USER_MENTEE_REGISTER_FAIL";

export const USER_MENTEE_SIGNIN_REQUEST = "USER_MENTEE_SIGNIN_REQUEST";
export const USER_MENTEE_SIGNIN_SUCCESS = "USER_MENTEE_SIGNIN_SUCCESS";
export const USER_MENTEE_SIGNIN_FAIL = "USER_MENTEE_SIGNIN_FAIL";

export const USER_MENTOR_SIGNIN_REQUEST = "USER_MENTOR_SIGNIN_REQUEST";
export const USER_MENTOR_SIGNIN_SUCCESS = "USER_MENTOR_SIGNIN_SUCCESS";
export const USER_MENTOR_SIGNIN_FAIL = "USER_MENTOR_SIGNIN_FAIL";

export const USER_MENTEE_SIGNOUT = "USER_SIGNOUT";
export const USER_MENTOR_SIGNOUT = "USER_SIGNOUT";

export const USER_MENTOR_DETAILS_REQUEST = "USER_MENTOR_DETAILS_REQUEST";
export const USER_MENTOR_DETAILS_SUCCESS = "USER_MENTOR_DETAILS_SUCCESS";
export const USER_MENTOR_DETAILS_FAIL = "USER_MENTOR_DETAILS_FAIL";
export const USER_MENTOR_DETAILS_RESET = "USER_MENTOR_DETAILS_RESET";

export const USER_MENTEE_DETAILS_REQUEST = "USER_MENTEE_DETAILS_REQUEST";
export const USER_MENTEE_DETAILS_SUCCESS = "USER_MENTEE_DETAILS_SUCCESS";
export const USER_MENTEE_DETAILS_FAIL = "USER_MENTEE_DETAILS_FAIL";
export const USER_MENTEE_DETAILS_RESET = "USER_MENTEE_DETAILS_RESET";

export const USER_MENTOR_LIST_REQUEST = "USER_MENTOR_LIST_REQUEST";
export const USER_MENTOR_LIST_SUCCESS = "USER_MENTOR_LIST_SUCCESS";
export const USER_MENTOR_LIST_FAIL = "USER_MENTOR_LIST_FAIL";

export const USER_MENTEE_LIST_REQUEST = "USER_MENTEE_LIST_REQUEST";
export const USER_MENTEE_LIST_SUCCESS = "USER_MENTEE_LIST_SUCCESS";
export const USER_MENTEE_LIST_FAIL = "USER_MENTEE_LIST_FAIL";

// export const USER_DELETE_REQUEST = "USER_DELETE_REQUEST";
// export const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS";
// export const USER_DELETE_FAIL = "USER_DELETE_FAIL";
// export const USER_DELETE_RESET = "USER_DELETE_RESET";

// export const USER_UPDATE_PROFILE_REQUEST = "USER_UPDATE_PROFILE_REQUEST";
// export const USER_UPDATE_PROFILE_SUCCESS = "USER_UPDATE_PROFILE_SUCCESS";
// export const USER_UPDATE_PROFILE_FAIL = "USER_UPDATE_PROFILE_FAIL";
// export const USER_UPDATE_PROFILE_RESET = "USER_UPDATE_PROFILE_RESET";

// export const USER_UPDATE_REQUEST = "USER_UPDATE_REQUEST";
// export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS";
// export const USER_UPDATE_FAIL = "USER_UPDATE_FAIL";
// export const USER_UPDATE_RESET = "USER_UPDATE_RESET";
